name: umitools_extract
description: Extract barcode and UMI from R2 and add to Read ID header
keywords:
  - umitools
  - extract
  - barcode
  - umi
  - read id
tools:
  - umi_tools:
      description: >
        UMI-tools contains tools for dealing with Unique Molecular Identifiers (UMIs)/Random
        Molecular Tags (RMTs) and single cell RNA-Seq cell barcodes

      documentation: https://umi-tools.readthedocs.io/en/latest/
      license: ["MIT"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fastq_r1:
        type: file
        description: |
          R1 FASTQ file containing barcode and UMI sequences.
        pattern: "*.{fastq,fastq.gz,fq,fq.gz}"
    - fastq_r2:
        type: file
        description: |
          R2 FASTQ file containing transcript sequences.
        pattern: "*.{fastq,fastq.gz,fq,fq.gz}"
  - - whitelist:
        type: file
        description: |
          Whitelist of valid cell barcodes generated by UMI-tools whitelist
        pattern: "*.{txt}"
  - - barcode_length:
        type: integer
        description: |
          Length of the cell barcode (default: 16 for 10X)
  - - umi_length:
        type: integer
        description: |
          Length of the UMI (default: 12 for 10X)
output:
  - extracted_fastq:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "${prefix}.extracted.fastq.gz":
          type: file
          description: FASTQ file with barcode and UMI in Read ID header
          pattern: "*.{fastq.gz,fq.gz}"
  - log:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.log":
          type: file
          description: File with logging information
          pattern: "*.{log}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@xuan13hao"
maintainers:
  - "@xuan13hao"
